import { Mold } from '../models/entities/mold';
import { Injectable } from '@angular/core';
import { DbServiceRepositoryBase } from '../core/database/db.service.repository.base';

@Injectable({
  providedIn: 'root',
})
export class MoldDbService extends DbServiceRepositoryBase<Mold> {
  data: Mold[] = [
    {
      id: 23,
      path: 'assets/home-slides-lg/mold1.png',
      mode: 'lg',
      name: 'Plastik Enjeksiyon Kalıpçılığı ve\nEndüstriyel Ürün Geliştirmede\n20 Yıllık Deneyim',
      description: '',
      moldId: 1,
    },
    {
      id: 24,
      path: 'assets/home-slides-lg/mold2.png',
      mode: 'lg',
      name: '',
      description: '',
      moldId: 2,
    },
    {
      id: 25,
      path: 'assets/home-slides-lg/mold3.png',
      mode: 'lg',
      name: '',
      description: '',
      moldId: 3,
    },
    {
      id: 26,
      path: 'assets/home-slides-lg/mold4.png',
      mode: 'lg',
      name: '',
      description: '',
      moldId: 4,
    },
    {
      id: 27,
      path: 'assets/home-slides-lg/mold5.png',
      mode: 'lg',
      name: '',
      description: '',
      moldId: 5,
    },
    {
      id: 28,
      path: 'assets/home-slides-lg/mold6.png',
      mode: 'lg',
      name: '',
      description: '',
      moldId: 6,
    },
    {
      id: 29,
      path: 'assets/home-slides-lg/mold7.png',
      mode: 'lg',
      name: '',
      description: '',
      moldId: 7,
    },
    {
      id: 30,
      path: 'assets/home-slides-lg/mold8.png',
      mode: 'lg',
      name: '',
      description: '',
      moldId: 8,
    },
    {
      id: 31,
      path: 'assets/home-slides-lg/mold9.png',
      mode: 'lg',
      name: '',
      description: '',
      moldId: 9,
    },
    {
      id: 32,
      path: 'assets/home-slides-lg/mold10.png',
      mode: 'lg',
      name: '',
      description: '',
      moldId: 10,
    },
    {
      id: 33,
      path: 'assets/home-slides-lg/mold11.png',
      mode: 'lg',
      name: '',
      description: '',
      moldId: 11,
    },
    {
      id: 34,
      path: 'assets/home-slides-lg/mold12.png',
      mode: 'lg',
      name: '',
      description: '',
      moldId: 12,
    },
    {
      id: 35,
      path: 'assets/home-slides-lg/mold13.png',
      mode: 'lg',
      name: '',
      description: '',
      moldId: 13,
    },
    {
      id: 36,
      path: 'assets/home-slides-lg/mold14.png',
      mode: 'lg',
      name: '',
      description: '',
      moldId: 14,
    },
    {
      id: 37,
      path: 'assets/home-slides-lg/mold15.png',
      mode: 'lg',
      name: '',
      description: '',
      moldId: 15,
    },
    {
      id: 38,
      path: 'assets/home-slides-lg/mold16.png',
      mode: 'lg',
      name: '',
      description: '',
      moldId: 16,
    },
    {
      id: 39,
      path: 'assets/home-slides-lg/mold17.png',
      mode: 'lg',
      name: '',
      description: '',
      moldId: 17,
    },
    {
      id: 40,
      path: 'assets/home-slides-lg/mold18.png',
      mode: 'lg',
      name: '',
      description: '',
      moldId: 18,
    },
    {
      id: 41,
      path: 'assets/home-slides-lg/mold19.png',
      mode: 'lg',
      name: '',
      description: '',
      moldId: 19,
    },
    {
      id: 42,
      path: 'assets/home-slides-lg/mold20.png',
      mode: 'lg',
      name: '',
      description: '',
      moldId: 20,
    },
    {
      id: 43,
      path: 'assets/home-slides-lg/mold21.png',
      mode: 'lg',
      name: '',
      description: '',
      moldId: 21,
    },
    {
      id: 44,
      path: 'assets/home-slides-lg/mold22.png',
      mode: 'lg',
      name: '',
      description: '',
      moldId: 22,
    },
    // SM IMAGES START
    {
      id: 45,
      path: 'assets/home-slides-sm/mold1-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 46,
      path: 'assets/home-slides-sm/mold2-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 47,
      path: 'assets/home-slides-sm/mold3-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 48,
      path: 'assets/home-slides-sm/mold4-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 49,
      path: 'assets/home-slides-sm/mold5-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 50,
      path: 'assets/home-slides-sm/mold6-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 51,
      path: 'assets/home-slides-sm/mold7-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 52,
      path: 'assets/home-slides-sm/mold8-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 53,
      path: 'assets/home-slides-sm/mold9-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 54,
      path: 'assets/home-slides-sm/mold10-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 55,
      path: 'assets/home-slides-sm/mold11-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 56,
      path: 'assets/home-slides-sm/mold12-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 57,
      path: 'assets/home-slides-sm/mold13-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 58,
      path: 'assets/home-slides-sm/mold14-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 59,
      path: 'assets/home-slides-sm/mold15-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 60,
      path: 'assets/home-slides-sm/mold16-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 61,
      path: 'assets/home-slides-sm/mold17-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 62,
      path: 'assets/home-slides-sm/mold18-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 63,
      path: 'assets/home-slides-sm/mold19-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 64,
      path: 'assets/home-slides-sm/mold20-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 65,
      path: 'assets/home-slides-sm/mold21-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 66,
      path: 'assets/home-slides-sm/mold22-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 67,
      path: 'assets/home-slides-sm/mold23-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    // FOR GALLERY
    // SM IMAGES START
    {
      id: 1,
      path: 'assets/gallery/mold1.jpeg',
      mode: 'all',
      name: 'Plastik Izgara Kalıbı',
      description:
        'Jeneratör havalandırma ızgarası\n2 gözlü\nHammadde: PA6 %30GFR',
    },
    {
      id: 2,
      path: 'assets/gallery/mold2.jpeg',
      mode: 'all',
      name: 'Mop Gövde Kalıbı',
      description: 'Sıcak yolluklu\n1 gözlü\nHammadde: PP',
    },
    {
      id: 3,
      path: 'assets/gallery/mold3.jpeg',
      mode: 'all',
      name: '30 ml Kuru Kahve Ölçeği Kalıbı',
      description: '8 gözlü\nTünel yolluklu\nHammadde: PP',
    },
    {
      id: 4,
      path: 'assets/gallery/mold4.jpeg',
      mode: 'all',
      name: '75 Motopomp Başlık Kalıbı',
      description: 'Dişi ve erkek tek kalıpta',
    },
    {
      id: 5,
      path: 'assets/gallery/mold5.jpeg',
      mode: 'all',
      name: 'Yağ Filtresi Muhafaza Kalıbı',
      description: 'Hammadde: PA6 %20GFR',
    },
    {
      id: 6,
      path: 'assets/gallery/mold6.jpeg',
      mode: 'all',
      name: 'Plastik Dişli Kalıbı',
      description: '24 ve 52 diş aynı kalıpta',
    },
    {
      id: 7,
      path: 'assets/gallery/mold7.jpeg',
      mode: 'all',
      name: 'Su Filtresi Çiftli Gövde Kalıbı',
      description: '4 adet hidrolik maça\nHammadde: PA6 %30GFR',
    },
    {
      id: 8,
      path: 'assets/gallery/mold8.jpeg',
      mode: 'all',
      name: 'Yağ Göstergesi Kalıbı',
      description: '4 gözlü\nHammadde: Şeffaf PC',
    },
    {
      id: 9,
      path: 'assets/gallery/mold9.jpeg',
      mode: 'all',
      name: 'Mop Bağlantı Adaptörü Kalıbı',
      description: '2 gözlü\n2 adet hidrolik maça\nHammadde: PP',
    },
    {
      id: 10,
      path: 'assets/gallery/mold10.jpeg',
      mode: 'all',
      name: 'Eksantrik Kol ve Tespit Pulu Kalıbı',
      description: 'İki ürün tek kalıpta',
    },
    {
      id: 11,
      path: 'assets/gallery/mold11.jpeg',
      mode: 'all',
      name: 'Su Filtreleme Diski Enjeksiyon Kalıbı',
      description: '4 gözlü\nSıcak manifold + sıcak yolluk + soğuk besleme',
    },
    {
      id: 12,
      path: 'assets/gallery/mold12.jpeg',
      mode: 'all',
      name: 'Mobilya Ayak Kapağı Kalıbı',
      description: '4 gözlü',
    },
    {
      id: 13,
      path: 'assets/gallery/mold13.jpeg',
      mode: 'all',
      name: 'Otomobil Yedek Parçası Kalıbı',
      description: 'Hammadde: ABS',
    },
    {
      id: 14,
      path: 'assets/gallery/mold14.jpeg',
      mode: 'all',
      name: 'ŞekerMatik Bileziği Kalıbı',
      description: '6 gözlü\nHammadde: Şeffaf Kristal',
    },
    {
      id: 15,
      path: 'assets/gallery/mold15.jpeg',
      mode: 'all',
      name: 'Kelebek Vana Plastik Klape Kalıbı',
      description: '2 adet hidrolik maça\nHammadde: PA6 %30GFR',
    },
    {
      id: 16,
      path: 'assets/gallery/mold16.jpeg',
      mode: 'all',
      name: 'Redüktör Gövdesi Plastik Enjeksiyon Kalıbı',
      description:
        'Hamur yoğurma makinesi redüktör gövdesi\nHammadde: PA6 %30GFR',
    },
    {
      id: 17,
      path: 'assets/gallery/mold17.jpeg',
      mode: 'all',
      name: 'Yağ Filtresi Alt Parçası Kalıbı',
      description: '4 gözlü\n2 adet hidrolik maça\nHammadde: PA6 %20GFR',
    },
    {
      id: 18,
      path: 'assets/gallery/mold18.jpeg',
      mode: 'all',
      name: 'Mobilya Ayak Gövdesi Kalıbı',
      description: '4 gözlü\nRedüktörlü',
    },
    {
      id: 19,
      path: 'assets/gallery/mold19.jpeg',
      mode: 'all',
      name: 'Yağ Filtresi Üst Parçası Kalıbı',
      description: '2 gözlü\nRedüktörlü\nHammadde: PA6 %20GFR',
    },
    {
      id: 20,
      path: 'assets/gallery/mold20.jpeg',
      mode: 'all',
      name: 'Su Filtresi Tekli Gövde Kalıbı',
      description: '3 adet hidrolik maça\nHammadde: PA6 %30GFR',
    },
    {
      id: 21,
      path: 'assets/gallery/mold21.jpeg',
      mode: 'all',
      name: 'Tripot Plastik Bağlantı Parçaları Kalıbı',
      description: '3 ürün tek kalıpta\nHammadde: PA6',
    },
    {
      id: 22,
      path: 'assets/gallery/mold22.jpeg',
      mode: 'all',
      name: 'Plastik TrumPlate Kalıbı',
      description: 'Asma köprü halat bağlantı parçası\nHammadde: PE',
    },
    // {
    //   id: 23,
    //   path: 'assets/gallery/mold23.jpeg',
    //   mode: 'all',
    //   name: 'Plastik Enjeksiyon Kalıpçılığı ve\nEndüstriyel Ürün Geliştirmede\n20 Yıllık Deneyim',
    //   description: '',
    // },
  ];
}
