import { Mold } from './../models/entities/mold';
import { Injectable } from '@angular/core';
import { DbServiceRepositoryBase } from '../core/database/db.service.repository.base';

@Injectable({
  providedIn: 'root',
})
export class MoldDbService extends DbServiceRepositoryBase<Mold> {
  data: Mold[] = [
    {
      id: 1,
      path: 'assets/home-slides-lg/mold1.png',
      mode: 'lg',
      name: '',
      description: '',
    },
    {
      id: 2,
      path: 'assets/home-slides-lg/mold2.png',
      mode: 'lg',
      name: '',
      description: '',
    },
    {
      id: 3,
      path: 'assets/home-slides-lg/mold3.png',
      mode: 'lg',
      name: '',
      description: '',
    },
    {
      id: 4,
      path: 'assets/home-slides-lg/mold4.png',
      mode: 'lg',
      name: '',
      description: '',
    },
    {
      id: 1,
      path: 'assets/home-slides-lg/mold5.png',
      mode: 'lg',
      name: '',
      description: '',
    },
    {
      id: 2,
      path: 'assets/home-slides-lg/mold6.png',
      mode: 'lg',
      name: '',
      description: '',
    },
    {
      id: 3,
      path: 'assets/home-slides-lg/mold7.png',
      mode: 'lg',
      name: '',
      description: '',
    },
    {
      id: 4,
      path: 'assets/home-slides-lg/mold8.png',
      mode: 'lg',
      name: '',
      description: '',
    },
    {
      id: 1,
      path: 'assets/home-slides-lg/mold9.png',
      mode: 'lg',
      name: '',
      description: '',
    },
    {
      id: 2,
      path: 'assets/home-slides-lg/mold10.png',
      mode: 'lg',
      name: '',
      description: '',
    },
    {
      id: 3,
      path: 'assets/home-slides-lg/mold11.png',
      mode: 'lg',
      name: '',
      description: '',
    },
    {
      id: 4,
      path: 'assets/home-slides-lg/mold12.png',
      mode: 'lg',
      name: '',
      description: '',
    },
    {
      id: 1,
      path: 'assets/home-slides-lg/mold13.png',
      mode: 'lg',
      name: '',
      description: '',
    },
    {
      id: 2,
      path: 'assets/home-slides-lg/mold14.png',
      mode: 'lg',
      name: '',
      description: '',
    },
    {
      id: 3,
      path: 'assets/home-slides-lg/mold15.png',
      mode: 'lg',
      name: '',
      description: '',
    },
    {
      id: 4,
      path: 'assets/home-slides-lg/mold16.png',
      mode: 'lg',
      name: '',
      description: '',
    },
    {
      id: 1,
      path: 'assets/home-slides-lg/mold17.png',
      mode: 'lg',
      name: '',
      description: '',
    },
    {
      id: 2,
      path: 'assets/home-slides-lg/mold18.png',
      mode: 'lg',
      name: '',
      description: '',
    },
    {
      id: 3,
      path: 'assets/home-slides-lg/mold19.png',
      mode: 'lg',
      name: '',
      description: '',
    },
    {
      id: 4,
      path: 'assets/home-slides-lg/mold20.png',
      mode: 'lg',
      name: '',
      description: '',
    },
    {
      id: 1,
      path: 'assets/home-slides-lg/mold21.png',
      mode: 'lg',
      name: '',
      description: '',
    },
    {
      id: 2,
      path: 'assets/home-slides-lg/mold22.png',
      mode: 'lg',
      name: '',
      description: '',
    },
    {
      id: 3,
      path: 'assets/home-slides-lg/mold23.png',
      mode: 'lg',
      name: '',
      description: '',
    },
    // SM IMAGES START
    {
      id: 5,
      path: 'assets/home-slides-sm/mold1-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 6,
      path: 'assets/home-slides-sm/mold2-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 7,
      path: 'assets/home-slides-sm/mold3-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 8,
      path: 'assets/home-slides-sm/mold4-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 5,
      path: 'assets/home-slides-sm/mold5-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 6,
      path: 'assets/home-slides-sm/mold6-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 7,
      path: 'assets/home-slides-sm/mold7-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 8,
      path: 'assets/home-slides-sm/mold8-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 5,
      path: 'assets/home-slides-sm/mold9-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 6,
      path: 'assets/home-slides-sm/mold10-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 7,
      path: 'assets/home-slides-sm/mold11-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 8,
      path: 'assets/home-slides-sm/mold12-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 5,
      path: 'assets/home-slides-sm/mold13-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 6,
      path: 'assets/home-slides-sm/mold14-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 7,
      path: 'assets/home-slides-sm/mold15-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 8,
      path: 'assets/home-slides-sm/mold16-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 5,
      path: 'assets/home-slides-sm/mold17-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 6,
      path: 'assets/home-slides-sm/mold18-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 7,
      path: 'assets/home-slides-sm/mold19-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 8,
      path: 'assets/home-slides-sm/mold20-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 5,
      path: 'assets/home-slides-sm/mold21-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 6,
      path: 'assets/home-slides-sm/mold22-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
    {
      id: 7,
      path: 'assets/home-slides-sm/mold23-sm.png',
      mode: 'sm',
      name: '',
      description: '',
    },
  ];
}
