import { Injectable } from '@angular/core';
import { DbServiceRepositoryBase } from '../core/database/db.service.repository.base';
import { Slide } from '../models/entities/slide';

@Injectable({
  providedIn: 'root',
})
export class SlideDbService extends DbServiceRepositoryBase<Slide> {
  data: Slide[] = [
    {
      id: 1,
      path: 'assets/home-slides-lg/mold1.webp',
      title:
        'slide1Title',
      description: '',
      type: 'lg',
    },
    {
      id: 2,
      path: 'assets/home-slides-lg/mold2.webp',
      title: 'mold14Title',
      description: 'mold14Description',
      type: 'lg',
    },
    {
      id: 3,
      path: 'assets/home-slides-lg/mold3.webp',
      title: 'mold10Title',
      description: 'mold10Description',
      type: 'lg',
    },
    {
      id: 4,
      path: 'assets/home-slides-lg/mold4.webp',
      title: 'mold5Title',
      description: 'mold5Description',
      type: 'lg',
    },
    {
      id: 5,
      path: 'assets/home-slides-lg/mold5.webp',
      title: 'mold3Title',
      description: 'mold3Description',
      type: 'lg',
    },
    {
      id: 6,
      path: 'assets/home-slides-lg/mold6.webp',
      title: 'mold16Title',
      description:
        'mold3Description',
      type: 'lg',
    },
    {
      id: 7,
      path: 'assets/home-slides-lg/mold7.webp',
      title: 'mold21Title',
      description: 'mold3Description',
      type: 'lg',
    },
    {
      id: 8,
      path: 'assets/home-slides-lg/mold8.webp',
      title: 'mold4Title',
      description: 'mold3Description',
      type: 'lg',
    },
    {
      id: 9,
      path: 'assets/home-slides-lg/mold9.webp',
      title: 'mold6Title',
      description: '24 ve 52 diş aynı kalıpta',
      type: 'lg',
    },
    {
      id: 10,
      path: 'assets/home-slides-lg/mold10.webp',
      title: 'mold11Title',
      description: '4 gözlü\nSıcak manifold + sıcak yolluk + soğuk besleme',
      type: 'lg',
    },
    {
      id: 11,
      path: 'assets/home-slides-lg/mold11.webp',
      title: 'mold12Title',
      description: '4 gözlü',
      type: 'lg',
    },
    {
      id: 12,
      path: 'assets/home-slides-lg/mold12.webp',
      title: 'mold13Title',
      description: 'Hammadde: ABS',
      type: 'lg',
    },
    {
      id: 13,
      path: 'assets/home-slides-lg/mold13.webp',
      title: 'mold22Title',
      description: 'Asma köprü halat bağlantı parçası\nHammadde: PE',
      type: 'lg',
    },
    {
      id: 14,
      path: 'assets/home-slides-lg/mold14.webp',
      title: 'mold8Title',
      description: '4 gözlü\nHammadde: Şeffaf PC',
      type: 'lg',
    },
    {
      id: 15,
      path: 'assets/home-slides-lg/mold15.webp',
      title: 'mold18Title',
      description: '4 gözlü\nRedüktörlü',
      type: 'lg',
    },
    {
      id: 16,
      path: 'assets/home-slides-lg/mold16.webp',
      title: 'mold6Title',
      description: '24 ve 52 diş aynı kalıpta',
      type: 'lg',
    },
    {
      id: 17,
      path: 'assets/home-slides-lg/mold17.webp',
      title: 'mold2Title',
      description: 'Sıcak yolluklu\n1 gözlü\nHammadde: PP',
      type: 'lg',
    },
    {
      id: 18,
      path: 'assets/home-slides-lg/mold18.webp',
      title: 'mold1Title',
      description:
        'Jeneratör havalandırma ızgarası\n2 gözlü\nHammadde: PA6 %30GFR',
      type: 'lg',
    },
    {
      id: 19,
      path: 'assets/home-slides-lg/mold19.webp',
      title: 'mold19Title',
      description: '2 gözlü\nRedüktörlü\nHammadde: PA6 %20GFR',
      type: 'lg',
    },
    {
      id: 20,
      path: 'assets/home-slides-lg/mold20.webp',
      title: 'mold15Title',
      description: '2 adet hidrolik maça\nHammadde: PA6 %30GFR',
      type: 'lg',
    },
    {
      id: 21,
      path: 'assets/home-slides-lg/mold21.webp',
      title: 'mold9Title',
      description: '2 gözlü\n2 adet hidrolik maça\nHammadde: PP',
      type: 'lg',
    },
    {
      id: 22,
      path: 'assets/home-slides-lg/mold22.webp',
      title: 'mold7Title',
      description: '4 adet hidrolik maça\nHammadde: PA6 %30GFR',
      type: 'lg',
    },
    // SM START
    {
      id: 23,
      path: 'assets/home-slides-sm/mold1-sm.webp',
      title:
        'slide1Title',
      description: '',
      type: 'sm',
    },
    {
      id: 24,
      path: 'assets/home-slides-sm/mold2-sm.webp',
      title: 'mold14Title',
      description: '6 gözlü\nHammadde: Şeffaf Kristal',
      type: 'sm',
    },
    {
      id: 25,
      path: 'assets/home-slides-sm/mold3-sm.webp',
      title: 'mold10Title',
      description: 'İki ürün tek kalıpta',
      type: 'sm',
    },
    {
      id: 26,
      path: 'assets/home-slides-sm/mold4-sm.webp',
      title: 'mold5Title',
      description: 'Hammadde: PA6 %20GFR',
      type: 'sm',
    },
    {
      id: 27,
      path: 'assets/home-slides-sm/mold5-sm.webp',
      title: 'mold3Title',
      description: '8 gözlü\nTünel yolluklu\nHammadde: PP',
      type: 'sm',
    },
    {
      id: 28,
      path: 'assets/home-slides-sm/mold6-sm.webp',
      title: 'mold16Title',
      description:
        'Hamur yoğurma makinesi redüktör gövdesi\nHammadde: PA6 %30GFR',
      type: 'sm',
    },
    {
      id: 29,
      path: 'assets/home-slides-sm/mold7-sm.webp',
      title: 'mold21Title',
      description: '3 ürün tek kalıpta\nHammadde: PA6',
      type: 'sm',
    },
    {
      id: 30,
      path: 'assets/home-slides-sm/mold8-sm.webp',
      title: 'mold4Title',
      description: 'Dişi ve erkek tek kalıpta',
      type: 'sm',
    },
    {
      id: 31,
      path: 'assets/home-slides-sm/mold9-sm.webp',
      title: 'mold6Title',
      description: '24 ve 52 diş aynı kalıpta',
      type: 'sm',
    },
    {
      id: 32,
      path: 'assets/home-slides-sm/mold10-sm.webp',
      title: 'mold11Title',
      description: '4 gözlü\nSıcak manifold + sıcak yolluk + soğuk besleme',
      type: 'sm',
    },
    {
      id: 33,
      path: 'assets/home-slides-sm/mold11-sm.webp',
      title: 'mold12Title',
      description: '4 gözlü',
      type: 'sm',
    },
    {
      id: 34,
      path: 'assets/home-slides-sm/mold12-sm.webp',
      title: 'mold13Title',
      description: 'Hammadde: ABS',
      type: 'sm',
    },
    {
      id: 35,
      path: 'assets/home-slides-sm/mold13-sm.webp',
      title: 'mold22Title',
      description: 'Asma köprü halat bağlantı parçası\nHammadde: PE',
      type: 'sm',
    },
    {
      id: 36,
      path: 'assets/home-slides-sm/mold14-sm.webp',
      title: 'mold8Title',
      description: '4 gözlü\nHammadde: Şeffaf PC',
      type: 'sm',
    },
    {
      id: 37,
      path: 'assets/home-slides-sm/mold15-sm.webp',
      title: 'mold18Title',
      description: '4 gözlü\nRedüktörlü',
      type: 'sm',
    },
    {
      id: 38,
      path: 'assets/home-slides-sm/mold16-sm.webp',
      title: 'mold6Title',
      description: '24 ve 52 diş aynı kalıpta',
      type: 'sm',
    },
    {
      id: 39,
      path: 'assets/home-slides-sm/mold17-sm.webp',
      title: 'mold2Title',
      description: 'Sıcak yolluklu\n1 gözlü\nHammadde: PP',
      type: 'sm',
    },
    {
      id: 40,
      path: 'assets/home-slides-sm/mold18-sm.webp',
      title: 'mold1Title',
      description:
        'Jeneratör havalandırma ızgarası\n2 gözlü\nHammadde: PA6 %30GFR',
      type: 'sm',
    },
    {
      id: 41,
      path: 'assets/home-slides-sm/mold19-sm.webp',
      title: 'mold19Title',
      description: '2 gözlü\nRedüktörlü\nHammadde: PA6 %20GFR',
      type: 'sm',
    },
    {
      id: 42,
      path: 'assets/home-slides-sm/mold20-sm.webp',
      title: 'mold15Title',
      description: '2 adet hidrolik maça\nHammadde: PA6 %30GFR',
      type: 'sm',
    },
    {
      id: 43,
      path: 'assets/home-slides-sm/mold21-sm.webp',
      title: 'mold9Title',
      description: '2 gözlü\n2 adet hidrolik maça\nHammadde: PP',
      type: 'sm',
    },
    {
      id: 44,
      path: 'assets/home-slides-sm/mold22-sm.webp',
      title: 'mold7Title',
      description: '4 adet hidrolik maça\nHammadde: PA6 %30GFR',
      type: 'sm',
    },
  ];
}
